# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
  #     desired widget in your `content/home/` folder.
  #   The weight parameter defines the order that the links will appear in.

main:
  - name: Main page
    url: /
    weight: 10
  - name: Background
    url: about/
    weight: 20
  - name: Mes travaux (FR)
    url: post/
    weight: 30
  - name: Tutoriels (FR)
    url: tutos/
    weight: 40
