---
title: "Position idéologique des cantons"
author: Vestin Cyuzuzo Hategekimana
date: '2022-04-08'
slug: position-ideologique-des-cantons
categories:
  - R
tags:
  - r
  - statistiques
  - recherche
subtitle: '[Code seulement]'
summary: 'Une analyse du positionnement idéologique des cantons en fonction de leur proportion de "oui" dans les initiatives populaires depuis 1866 en utilisant une analyse en composante principale'
authors: []
lastmod: '2022-04-08T10:59:44+02:00'
featured: no
image:
  caption: ''
  focal_point: ''
  preview_only: no
projects: []
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE)
```

```{r}
library(tidyverse)
library(FactoMineR)
library(factoextra)
```

```{r}
load("votation.Rda")
```

```{r include=FALSE}
glimpse(votation)
```

```{r}
v_pca <-
  votation %>% 
  group_by(canton,id_objet) %>% 
  filter(date==last(date)) %>% 
  select(-date) %>% 
  ungroup() %>% 
  spread(id_objet,oui_en,drop = TRUE) 
```

```{r}
pca <- 
  v_pca %>%
  column_to_rownames("canton") %>% 
  PCA(graph = FALSE)
```

```{r}
get_eigenvalue(pca) %>% 
  head()
```

```{r}
fviz_eig(pca, addlabels = TRUE, ylim = c(0, 50))
```

```{r}
var_info <- get_pca_var(pca)
var_info
```

```{r}
tab_dim <- 
  var_info$cor[,1:2] %>% 
  as.data.frame() %>% 
  rownames_to_column("objet") %>% 
  arrange(objet) %>% 
  filter(Dim.1>=0.75 | Dim.1<=-0.75 | Dim.2>=0.75 | Dim.2<=-0.75)

dim1p <- tab_dim %>% filter(Dim.1 >=0.75) %>% arrange(desc(Dim.1)) %>% pull(objet)
dim1m <- tab_dim %>% filter(Dim.1 <=-0.75) %>% arrange(desc(Dim.1)) %>% pull(objet)
dim2p <- tab_dim %>% filter(Dim.2 >=0.75) %>% arrange(desc(Dim.2)) %>% pull(objet)
dim2m <- tab_dim %>% filter(Dim.2 <=-0.75) %>% arrange(desc(Dim.2)) %>% pull(objet)
```

```{r}
tab_dim %>%
  DT::datatable(filter="bottom")
```


```{r}
# Gauche
tab_dim %>% 
  select(id_objet=objet,dim1=Dim.1,dim2=Dim.2) %>% 
  full_join(index) %>% 
  top_n(10,dim1)
# Droite
tab_dim %>% 
  select(id_objet=objet,dim1=Dim.1,dim2=Dim.2) %>% 
  full_join(index) %>% 
  top_n(-10,dim1)

# Circulation
tab_dim %>% 
  select(id_objet=objet,dim1=Dim.1,dim2=Dim.2) %>% 
  full_join(index) %>% 
  top_n(10,dim2)
# 
tab_dim %>% 
  select(id_objet=objet,dim1=Dim.1,dim2=Dim.2) %>% 
  full_join(index) %>% 
  top_n(-20,dim2)
```


```{r fig.width=8}
fviz_pca_var(pca, col.var = "cos2",
             gradient.cols = c("#00AFBB", "#E7B800", "#FC4E07"),
             repel = TRUE)
```

```{r}
fviz_contrib(pca, choice = "var", axes = 1, top = 10)
fviz_contrib(pca, choice = "var", axes = 2, top = 10)
```


```{r}
fviz_pca_var(pca, col.var = "contrib",
             gradient.cols = c("#00AFBB", "#E7B800", "#FC4E07"))
```

```{r}
index %>% 
  DT::datatable(filter="bottom")
```

```{r fig.width=6}
fviz_pca_ind(pca, col.ind = "cos2", pointsize = "cos2",
             gradient.cols = c("#00AFBB", "#E7B800", "#FC4E07"),
             repel = TRUE 
             ) + 
  labs(title = "Classification des cantons selon leur attitudes de votes",
       x = "Droite                                                                        Gauche",
       y = "Liberal                                                                    Etat fort")
```

```{r}
vot_cor <- 
  var_info$cor %>% 
  as.data.frame() %>% 
  rownames_to_column("id_objet") %>% 
  select(1:3) %>% 
  janitor::clean_names() 

vot_cor %>% 
  ggplot(aes(dim_1,dim_2)) +
  geom_point()
```
